# Generated by Django 3.2.23 on 2023-11-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20231103_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='base_currency',
            new_name='base',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='quote_currency',
            new_name='quote',
        ),
    ]
