# Generated by Django 3.2.23 on 2023-11-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20231103_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='last_checked',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='last_rate',
        ),
    ]
