# Generated by Django 3.2.23 on 2023-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20231103_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
