# Generated by Django 3.2.23 on 2023-11-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alert_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='warning',
            field=models.BooleanField(default=False),
        ),
    ]
